/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/sr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Sr */
        get: operations["health_sr_health_sr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/sr-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sr Preview */
        get: operations["sr_preview_employees_sr_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/import-from-sr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import From Sr */
        post: operations["import_from_sr_employees_import_from_sr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_employees__employee_id__patch"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_settings_get"];
        /** Write Settings */
        put: operations["write_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_rest_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_rest_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_rest_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_rest_rules__rule_id__patch"];
        trace?: never;
    };
    "/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exceptions */
        get: operations["list_exceptions_exceptions_get"];
        put?: never;
        /** Create Exception */
        post: operations["create_exception_exceptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exceptions/rest-swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rest Swap */
        post: operations["create_rest_swap_exceptions_rest_swap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exceptions/{exception_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Exception */
        delete: operations["delete_exception_exceptions__exception_id__delete"];
        options?: never;
        head?: never;
        /** Update Exception */
        patch: operations["update_exception_exceptions__exception_id__patch"];
        trace?: never;
    };
    "/justifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Justifications */
        get: operations["list_justifications_justifications_get"];
        put?: never;
        /** Create Justification */
        post: operations["create_justification_justifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/justifications/{justification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Justification */
        delete: operations["delete_justification_justifications__justification_id__delete"];
        options?: never;
        head?: never;
        /** Update Justification */
        patch: operations["update_justification_justifications__justification_id__patch"];
        trace?: never;
    };
    "/attendance/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_attendance_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents */
        get: operations["incidents_attendance_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_attendance_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Xlsx */
        get: operations["export_xlsx_attendance_export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Area
         * @enum {string}
         */
        Area: "KITCHEN" | "OTHER";
        /** CalendarOut */
        CalendarOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Employees */
            employees: components["schemas"]["EmployeeRef"][];
            /** Days */
            days: components["schemas"]["DayOut"][];
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
        };
        /** DayOut */
        DayOut: {
            /** Employee Id */
            employee_id: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            planned: components["schemas"]["Planned"];
            outcome: components["schemas"]["Outcome"];
            /** Checkin */
            checkin: string | null;
            /** Minutes Late */
            minutes_late: number | null;
            rh_type: components["schemas"]["RhType"] | null;
            /** Justification Id */
            justification_id: number | null;
            /** Comment */
            comment: string;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Sr Id */
            sr_id?: number | null;
            /** Short Name */
            short_name: string;
            /** Rh Name */
            rh_name?: string | null;
            /** @default OTHER */
            area: components["schemas"]["Area"];
            /**
             * Applies Lateness
             * @default true
             */
            applies_lateness: boolean;
            /**
             * Tracks Attendance
             * @default true
             */
            tracks_attendance: boolean;
        };
        /** EmployeeOut */
        EmployeeOut: {
            /** Id */
            id: number;
            /** Sr Id */
            sr_id: number | null;
            /** Short Name */
            short_name: string;
            /** Rh Name */
            rh_name: string | null;
            area: components["schemas"]["Area"];
            /** Applies Lateness */
            applies_lateness: boolean;
            /** Tracks Attendance */
            tracks_attendance: boolean;
            /** Active */
            active: boolean;
        };
        /** EmployeeRef */
        EmployeeRef: {
            /** Id */
            id: number;
            /** Short Name */
            short_name: string;
            /** Rh Name */
            rh_name: string | null;
            area: components["schemas"]["Area"];
        };
        /** EmployeeUpdate */
        EmployeeUpdate: {
            /** Short Name */
            short_name?: string | null;
            /** Rh Name */
            rh_name?: string | null;
            area?: components["schemas"]["Area"] | null;
            /** Applies Lateness */
            applies_lateness?: boolean | null;
            /** Tracks Attendance */
            tracks_attendance?: boolean | null;
            /** Active */
            active?: boolean | null;
        };
        /** Envelope[CalendarOut] */
        Envelope_CalendarOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["CalendarOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[EmployeeOut] */
        Envelope_EmployeeOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["EmployeeOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[ExceptionOut] */
        Envelope_ExceptionOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ExceptionOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[HealthOut] */
        Envelope_HealthOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["HealthOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[IncidentsOut] */
        Envelope_IncidentsOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["IncidentsOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[JustificationOut] */
        Envelope_JustificationOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["JustificationOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[NoneType] */
        Envelope_NoneType_: {
            /** Success */
            success: boolean;
            /** Data */
            data?: null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[RestRuleOut] */
        Envelope_RestRuleOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["RestRuleOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[SettingsBody] */
        Envelope_SettingsBody_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SettingsBody"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[SrHealthOut] */
        Envelope_SrHealthOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SrHealthOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[EmployeeOut]] */
        Envelope_list_EmployeeOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["EmployeeOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[ExceptionOut]] */
        Envelope_list_ExceptionOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["ExceptionOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[JustificationOut]] */
        Envelope_list_JustificationOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["JustificationOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[RestRuleOut]] */
        Envelope_list_RestRuleOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["RestRuleOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[SrEmployeeOut]] */
        Envelope_list_SrEmployeeOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["SrEmployeeOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[SummaryOut]] */
        Envelope_list_SummaryOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["SummaryOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ExceptionCreate */
        ExceptionCreate: {
            kind: components["schemas"]["ExceptionKind"];
            /** Employee Id */
            employee_id?: number | null;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            rh_type?: components["schemas"]["RhType"] | null;
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /**
         * ExceptionKind
         * @enum {string}
         */
        ExceptionKind: "STORE_CLOSED" | "PRESENT_NO_CHECKIN" | "REST_TO_WORK" | "WORK_TO_ABSENCE" | "MANUAL_ABSENCE";
        /** ExceptionOut */
        ExceptionOut: {
            /** Id */
            id: number;
            kind: components["schemas"]["ExceptionKind"];
            /** Employee Id */
            employee_id: number | null;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            rh_type: components["schemas"]["RhType"] | null;
            /** Comment */
            comment: string;
        };
        /** ExceptionUpdate */
        ExceptionUpdate: {
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            rh_type?: components["schemas"]["RhType"] | null;
            /** Comment */
            comment?: string | null;
        };
        /**
         * Grouping
         * @enum {string}
         */
        Grouping: "week" | "month";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Db */
            db: string;
        };
        /** ImportRequest */
        ImportRequest: {
            /** Sr Ids */
            sr_ids: number[];
        };
        /**
         * Incident
         * @enum {string}
         */
        Incident: "LATE" | "ABSENT";
        /** IncidentsOut */
        IncidentsOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Incidents */
            incidents: components["schemas"]["DayOut"][];
            /** Rh Rows */
            rh_rows: components["schemas"]["RhRowOut"][];
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
        };
        /** JustificationCreate */
        JustificationCreate: {
            /** Employee Id */
            employee_id: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            incident: components["schemas"]["Incident"];
            /** Reason */
            reason: string;
            rh_type?: components["schemas"]["RhType"] | null;
        };
        /** JustificationOut */
        JustificationOut: {
            /** Id */
            id: number;
            /** Employee Id */
            employee_id: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            incident: components["schemas"]["Incident"];
            /** Reason */
            reason: string;
            rh_type: components["schemas"]["RhType"];
        };
        /** JustificationUpdate */
        JustificationUpdate: {
            /** Reason */
            reason?: string | null;
            rh_type?: components["schemas"]["RhType"] | null;
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "OK" | "LATE" | "ABSENT" | "UNREGISTERED_CHANGE" | "REST" | "CLOSED" | "JUSTIFIED" | "PENDING" | "FUTURE";
        /**
         * Planned
         * @enum {string}
         */
        Planned: "WORK" | "REST" | "CLOSED" | "ABSENCE";
        /** RestRuleCreate */
        RestRuleCreate: {
            /** Employee Id */
            employee_id: number;
            /** Fixed Weekday */
            fixed_weekday: number;
            /** Extra Weekday */
            extra_weekday: number;
            /**
             * Double Rest Anchor
             * Format: date
             */
            double_rest_anchor: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
        };
        /** RestRuleOut */
        RestRuleOut: {
            /** Id */
            id: number;
            /** Employee Id */
            employee_id: number;
            /** Fixed Weekday */
            fixed_weekday: number;
            /** Extra Weekday */
            extra_weekday: number;
            /**
             * Double Rest Anchor
             * Format: date
             */
            double_rest_anchor: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /** RestRuleUpdate */
        RestRuleUpdate: {
            /** Fixed Weekday */
            fixed_weekday?: number | null;
            /** Extra Weekday */
            extra_weekday?: number | null;
            /** Double Rest Anchor */
            double_rest_anchor?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** RestSwapCreate */
        RestSwapCreate: {
            /** Employee Id */
            employee_id: number;
            /**
             * Absent Day
             * Format: date
             */
            absent_day: string;
            /**
             * Worked Day
             * Format: date
             */
            worked_day: string;
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** RhRowOut */
        RhRowOut: {
            /** Employee Id */
            employee_id: number;
            /** Name */
            name: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            rh_type: components["schemas"]["RhType"];
            /** Comment */
            comment: string;
        };
        /**
         * RhType
         * @description Incident types of the HR tool, plus NO_CAPTURAR (justified, not reported).
         * @enum {string}
         */
        RhType: "RETARDO" | "FALTA_INJUSTIFICADA" | "FALTA_JUSTIFICADA" | "VACACIONES" | "INCAPACIDAD" | "PERMISO" | "DESCANSO" | "NO_CAPTURAR";
        /** SettingsBody */
        SettingsBody: {
            /**
             * Entry Time Kitchen
             * @example 16:40
             */
            entry_time_kitchen: string;
            /**
             * Entry Time Other
             * @example 16:40
             */
            entry_time_other: string;
            /** Tolerance Minutes */
            tolerance_minutes: number;
        };
        /** SrEmployeeOut */
        SrEmployeeOut: {
            /** Sr Id */
            sr_id: number;
            /** Name */
            name: string;
            /** Visible */
            visible: boolean;
            /** Imported */
            imported: boolean;
        };
        /** SrHealthOut */
        SrHealthOut: {
            /** Mode */
            mode: string;
            /** Server */
            server: string;
            /** Instance */
            instance: string;
            /** Version */
            version: string;
            /** Edition */
            edition: string;
            /** Database */
            database: string;
            /** Login */
            login: string;
            /** Is Datareader */
            is_datareader: boolean;
            /** Is Denywriter */
            is_denywriter: boolean;
            /** Is Sysadmin */
            is_sysadmin: boolean;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Employee Id */
            employee_id: number;
            /** Period */
            period: string;
            /** Worked */
            worked: number;
            /** Late */
            late: number;
            /** Late Justified */
            late_justified: number;
            /** Absent */
            absent: number;
            /** Absent Justified */
            absent_justified: number;
            /** Justified By Type */
            justified_by_type: {
                [key: string]: number;
            };
            /** Unresolved */
            unresolved: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningCode
         * @enum {string}
         */
        WarningCode: "NO_REST_RULE" | "UNMAPPED_CHECKIN" | "ORPHAN_JUSTIFICATION" | "MISSING_RH_NAME";
        /** WarningOut */
        WarningOut: {
            code: components["schemas"]["WarningCode"];
            /** Employee Id */
            employee_id: number | null;
            /** Day */
            day: string | null;
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthOut_"];
                };
            };
        };
    };
    health_sr_health_sr_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SrHealthOut_"];
                };
            };
        };
    };
    list_employees_employees_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_EmployeeOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EmployeeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sr_preview_employees_sr_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_SrEmployeeOut__"];
                };
            };
        };
    };
    import_from_sr_employees_import_from_sr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_EmployeeOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EmployeeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EmployeeOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SettingsBody_"];
                };
            };
        };
    };
    write_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SettingsBody_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_rest_rules_get: {
        parameters: {
            query?: {
                employee_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_RestRuleOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_rest_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RestRuleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_rest_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_rest_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RestRuleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exceptions_exceptions_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                employee_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ExceptionOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exception_exceptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExceptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExceptionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rest_swap_exceptions_rest_swap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestSwapCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ExceptionOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exception_exceptions__exception_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exception_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exception_exceptions__exception_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exception_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExceptionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExceptionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_justifications_justifications_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                employee_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_JustificationOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_justification_justifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JustificationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_JustificationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_justification_justifications__justification_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                justification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_justification_justifications__justification_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                justification_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JustificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_JustificationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_attendance_calendar_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CalendarOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incidents_attendance_incidents_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IncidentsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_attendance_summary_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                group?: components["schemas"]["Grouping"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_SummaryOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_xlsx_attendance_export_xlsx_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libro de Excel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
