"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 10:24:25.497811

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sr_id", sa.Integer(), nullable=True),
        sa.Column("short_name", sa.String(length=80), nullable=False),
        sa.Column("rh_name", sa.String(length=160), nullable=True),
        sa.Column(
            "area",
            sa.Enum("KITCHEN", "OTHER", name="area", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("applies_lateness", sa.Boolean(), nullable=False),
        sa.Column("tracks_attendance", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee")),
        sa.UniqueConstraint("sr_id", name=op.f("uq_employee_sr_id")),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_setting")),
    )
    op.create_table(
        "justification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column(
            "incident",
            sa.Enum("LATE", "ABSENT", name="incident", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "rh_type",
            sa.Enum(
                "RETARDO",
                "FALTA_INJUSTIFICADA",
                "FALTA_JUSTIFICADA",
                "VACACIONES",
                "INCAPACIDAD",
                "PERMISO",
                "DESCANSO",
                "NO_CAPTURAR",
                name="rhtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
            name=op.f("fk_justification_employee_id_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_justification")),
        sa.UniqueConstraint(
            "employee_id", "day", "incident", name=op.f("uq_justification_employee_id")
        ),
    )
    op.create_index(
        op.f("ix_justification_employee_id"), "justification", ["employee_id"], unique=False
    )
    op.create_table(
        "rest_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("fixed_weekday", sa.SmallInteger(), nullable=False),
        sa.Column("extra_weekday", sa.SmallInteger(), nullable=False),
        sa.Column("double_rest_anchor", sa.Date(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "extra_weekday BETWEEN 0 AND 6", name=op.f("ck_rest_rule_extra_weekday_range")
        ),
        sa.CheckConstraint(
            "fixed_weekday <> extra_weekday", name=op.f("ck_rest_rule_distinct_weekdays")
        ),
        sa.CheckConstraint(
            "fixed_weekday BETWEEN 0 AND 6", name=op.f("ck_rest_rule_fixed_weekday_range")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from <= valid_to", name=op.f("ck_rest_rule_valid_range")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
            name=op.f("fk_rest_rule_employee_id_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rest_rule")),
    )
    op.create_index(op.f("ix_rest_rule_employee_id"), "rest_rule", ["employee_id"], unique=False)
    op.create_table(
        "schedule_exception",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "STORE_CLOSED",
                "PRESENT_NO_CHECKIN",
                "REST_TO_WORK",
                "WORK_TO_ABSENCE",
                "MANUAL_ABSENCE",
                name="exceptionkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column(
            "rh_type",
            sa.Enum(
                "RETARDO",
                "FALTA_INJUSTIFICADA",
                "FALTA_JUSTIFICADA",
                "VACACIONES",
                "INCAPACIDAD",
                "PERMISO",
                "DESCANSO",
                "NO_CAPTURAR",
                name="rhtype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("comment", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(employee_id IS NULL) = (kind = 'STORE_CLOSED')",
            name=op.f("ck_schedule_exception_closure_has_no_employee"),
        ),
        sa.CheckConstraint(
            "(rh_type IS NOT NULL) = (kind = 'WORK_TO_ABSENCE')",
            name=op.f("ck_schedule_exception_absence_has_rh_type"),
        ),
        sa.CheckConstraint("date_from <= date_to", name=op.f("ck_schedule_exception_date_range")),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
            name=op.f("fk_schedule_exception_employee_id_employee"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_exception")),
    )
    op.create_index(
        op.f("ix_schedule_exception_employee_id"),
        "schedule_exception",
        ["employee_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    setting = sa.table("setting", sa.column("key", sa.String), sa.column("value", sa.String))
    op.bulk_insert(
        setting,
        [
            {"key": "entry_time_kitchen", "value": "16:30"},
            {"key": "entry_time_other", "value": "16:40"},
            {"key": "tolerance_minutes", "value": "10"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_exception_employee_id"), table_name="schedule_exception")
    op.drop_table("schedule_exception")
    op.drop_index(op.f("ix_rest_rule_employee_id"), table_name="rest_rule")
    op.drop_table("rest_rule")
    op.drop_index(op.f("ix_justification_employee_id"), table_name="justification")
    op.drop_table("justification")
    op.drop_table("setting")
    op.drop_table("employee")
    # ### end Alembic commands ###
